### ISSUE TITLE
how to use unspervised learning to choose best translation 

### ISSUE THREAD

**Issue by sevilaybayatli** [apertium/apertium-kaz-tur#1]
Hi,
I am going to make a module to get the best translation among ambiguous translation  and for this, I am going to use unsupervised algorithms before that I parsed transfer rules and weighting them now the next step how can I use machine learning to learn the weight If anyone has an idea please help me and my data look like:  

sentence id ||| coverage id ||| original sentence ||| lextor ||| rules ||| chunker ||| final sentence ||| score
1  ||| 1  ||| - XXI ғасырда біздің Конституциямызды жаңаша оқу қажет. ||| ^-<guio>/-<guio>$ ^XXI<num><ord>/XXI<num><ord>$ ^ғасыр<n><loc>/asır<n><loc>/alim<n><loc>/yüzyıl<n><loc>$ ^біз<prn><pers><p1><pl><gen>/biz<prn><pers><p1><pl><gen>$ ^Конституция<n><px1pl><acc>/Anayasa<n><px1pl><acc>/Bünye<n><px1pl><acc>$ ^жаңаша<adv>/farklı şekilde<adv>$ ^оқы<v><tv><ger><nom>/oku<v><tv><ger><nom>/çalış<v><iv><ger><nom>$ ^қажет<n><nom>/zaruret<n><nom>$ ^е<cop><aor><p3><sg>/i<cop><aor><p3><sg>$^.<sent>/.<sent>$^.<sent>/.<sent>$ ||| 31 12 67 76 76 ||| ^default<default>{^-<guio>$}$ ^default<default>{^XXI<num><ord>$}$ ^default<default>{^asır<n><loc>$}$ ^n<SN>{^biz<prn><pers><p1><pl><gen>$ ^Anayasa<n><px1pl><acc>$}$ ^default<default>{^farklı şekilde<adv>$}$ ^v-ger<SV>{^oku<v><tv><ger_inf><nom>$}$ ^default<default>{^zaruret<n><nom>$}$ ^v<SV>{^i<cop><aor><p3><sg>$}$^sent<SENT>{^.<sent>$}$^sent<SENT>{^.<sent>$}$ |||  - XXI asırda bizim Anayasamızı farklı şekilde okumak zaruret. |||0.0714

1 ||| 2 ||| - XXI ғасырда біздің Конституциямызды жаңаша оқу қажет. ||| ^-<guio>/-<guio>$ ^XXI<num><ord>/XXI<num><ord>$ ^ғасыр<n><loc>/asır<n><loc>/alim<n><loc>/yüzyıl<n><loc>$ ^біз<prn><pers><p1><pl><gen>/biz<prn><pers><p1><pl><gen>$ ^Конституция<n><px1pl><acc>/Anayasa<n><px1pl><acc>/Bünye<n><px1pl><acc>$ ^жаңаша<adv>/farklı şekilde<adv>$ ^оқы<v><tv><ger><nom>/oku<v><tv><ger><nom>/çalış<v><iv><ger><nom>$ ^қажет<n><nom>/zaruret<n><nom>$ ^е<cop><aor><p3><sg>/i<cop><aor><p3><sg>$^.<sent>/.<sent>$^.<sent>/.<sent>$ ||| 32 12  67 76 76 ||| ^default<default>{^-<guio>$}$ ^default<default>{^XXI<num><ord>$}$ ^default<default>{^asır<n><loc>$}$ ^n<SN>{^Anayasa<n><nom>$}$ ^default<default>{^farklı şekilde<adv>$}$ ^v<SV>{^bul<v><tv><ger_inf><nom>$}$ ^default<default>{^zaruret<n><nom>$}$ ^v<SV>{^i<cop><aor><p3><sg>$}$^sent<SENT>{^.<sent>$}$^sent<SENT>{^.<sent>$}$ ||| - XXI asırda Anayasamızı farklı şekilde okumak zaruret.   |||  0.2767

1 ||| 3 ||| - XXI ғасырда біздің Конституциямызды жаңаша оқу қажет. ||| ^-<guio>/-<guio>$ ^XXI<num><ord>/XXI<num><ord>$ ^ғасыр<n><loc>/asır<n><loc>/alim<n><loc>/yüzyıl<n><loc>$ ^біз<prn><pers><p1><pl><gen>/biz<prn><pers><p1><pl><gen>$ ^Конституция<n><px1pl><acc>/Anayasa<n><px1pl><acc>/Bünye<n><px1pl><acc>$ ^жаңаша<adv>/farklı şekilde<adv>$ ^оқы<v><tv><ger><nom>/oku<v><tv><ger><nom>/çalış<v><iv><ger><nom>$ ^қажет<n><nom>/zaruret<n><nom>$ ^е<cop><aor><p3><sg>/i<cop><aor><p3><sg>$^.<sent>/.<sent>$^.<sent>/.<sent>$ ||| 31 13  67 76 76 |||  ^default<default>{^-<guio>$}$ ^default<default>{^XXI<num><ord>$}$ ^default<default>{^asır<n><loc>$}$ ^n<SN>{^biz<prn><pers><p1><pl><gen>$ ^Anayasa<n><px1pl><acc>$}$ ^default<default>{^farklı şekilde<adv>$}$ ^v-ger<SV>{^oku<v><tv><ger><nom>$}$ ^default<default>{^zaruret<n><nom>$}$ ^v<SV>{^i<cop><aor><p3><sg>$}$^sent<SENT>{^.<sent>$}$^sent<SENT>{^.<sent>$}$ ||| - XXI asırda bizim Anayasamızı farklı şekilde okuma zaruret.  |||  0.1933

1 ||| 4 ||| - XXI ғасырда біздің Конституциямызды жаңаша оқу қажет. ||| ^-<guio>/-<guio>$ ^XXI<num><ord>/XXI<num><ord>$ ^ғасыр<n><loc>/asır<n><loc>/alim<n><loc>/yüzyıl<n><loc>$ ^біз<prn><pers><p1><pl><gen>/biz<prn><pers><p1><pl><gen>$ ^Конституция<n><px1pl><acc>/Anayasa<n><px1pl><acc>/Bünye<n><px1pl><acc>$ ^жаңаша<adv>/farklı şekilde<adv>$ ^оқы<v><tv><ger><nom>/oku<v><tv><ger><nom>/çalış<v><iv><ger><nom>$ ^қажет<n><nom>/zaruret<n><nom>$ ^е<cop><aor><p3><sg>/i<cop><aor><p3><sg>$^.<sent>/.<sent>$^.<sent>/.<sent>$ ||| 32 13 67 76 76 ||| ^default<default>{^-<guio>$}$ ^default<default>{^XXI<num><ord>$}$ ^default<default>{^asır<n><loc>$}$ ^n<SN>{^Anayasa<n><nom>$}$ ^default<default>{^farklı şekilde<adv>$}$ ^v<SV>{^bul<v><tv><ger_inf><nom>$}$ ^default<default>{^zaruret<n><nom>$}$ ^v<SV>{^i<cop><aor><p3><sg>$}$^sent<SENT>{^.<sent>$}$^sent<SENT>{^.<sent>$}$||| ^v-ger<SV>{^oku<v><tv><ger><nom>$}$ ||| - XXI asırda Anayasamızı farklı şekilde okuma zaruret.|||0.2757

**Comment by MemduhG** [comment]
I don't know about the weighting part but for choosing the best translation I think you would need to decide which one is the most _likely_ translation of all, based on a language model. I think @ftyers suggested to use N-grams, so you would find which sequences of words are more frequent in your  target language, in this case Turkish I believe. 

I am not very well acquainted with language models myself, but as far as I understand if it's a 5-gram model, you find statistics on all 5-word sequences in a corpus. It would amount to a long list of frequency counts, which would be used for weighting the rules. I hope someone will correct me if I am mistaken. 

This module of sci-kit learn seems to be useful for this purpose: http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

Edit: here's a nice intro Jurafsky wrote on n-gram models: https://web.stanford.edu/~jurafsky/slp3/4.pdf
